"""Config scaffolding for the `reveille init` command.

Provides the annotated default TOML template and the write function
that materialises it on disk. This module has no knowledge of the CLI
layer -- it accepts a resolved path and a force flag, writes the file,
and returns the absolute path.
"""

from __future__ import annotations

from pathlib import Path

from reveille.exceptions import ConfigurationError, OutputPathError

# ---------------------------------------------------------------------------
# Annotated default configuration template
# ---------------------------------------------------------------------------
# All keys are commented out. Users uncomment only the keys they want to
# override. The comments are the primary documentation surface for
# first-time users who have not yet consulted the User Guide.
# ASCII separators are used throughout -- no Unicode box-drawing characters.
# ---------------------------------------------------------------------------

_DEFAULT_CONFIG_TEMPLATE: str = """\
# reveille.toml -- Configuration file for Reveille
#
# Generated by `reveille init`. Uncomment and edit the keys you need.
# All keys are optional. CLI flags always take precedence over values here.
# Full reference:
#   https://github.com/varaprasadchilakanti/reveille/blob/main/docs/USER_GUIDE.md

# ------------------------------------------------------------------------------
# [report] -- Core report parameters
# ------------------------------------------------------------------------------

[report]

# Override the report title displayed in the HTML output.
# Defaults to the repository directory name.
# title = "Engineering Performance Report"

# Output path for the generated HTML file.
# The parent directory must exist at generation time.
# Defaults to ./reveille-report.html at the repository root.
# output = "./reveille-report.html"

# Analyse commits reachable from this branch only.
# Defaults to the repository's currently active branch.
# branch = "main"

# Include only commits on or after this date (YYYY-MM-DD).
# Defaults to the date of the repository's first commit.
# since = "2024-01-01"

# Include only commits on or before this date (YYYY-MM-DD).
# Defaults to today.
# until = "2024-12-31"

# Resolution of the commit activity heatmap.
# Accepted values: "daily", "weekly", "monthly", "yearly"
#   daily   -- one cell per calendar day (GitHub-style). Rolling 365-day window.
#              Best for active repositories where per-day granularity is meaningful.
#   weekly  -- one column per calendar week.
#              Best for repositories with fewer than 6 months of history.
#   monthly -- one column per calendar month. Default. Suits most repositories.
#   yearly  -- one column per year.
#              Best for repositories with more than 3 years of history.
# heatmap_granularity = "monthly"


# ------------------------------------------------------------------------------
# [filters] -- Contributor and commit filtering
# ------------------------------------------------------------------------------

[filters]

# Exclude contributors with fewer than this many commits in the analysis window.
# Must be a positive integer. Useful for filtering one-off contributors that
# would otherwise distort ranking percentiles in small populations.
# min_commits = 1

# Exclude contributors by name or email address. Case-insensitive.
# Both display name and email forms are accepted. Specify as a TOML array.
# exclude_authors = [
#     "dependabot[bot]",
#     "github-actions[bot]",
# ]


# ------------------------------------------------------------------------------
# [ranking] -- Contributor ranking engine
# ------------------------------------------------------------------------------

[ranking]

# Set to false to omit the contributor ranking table from the output entirely.
# enabled = true

# Metric weights for the composite ranking score.
# All four values must sum to exactly 1.0.
#
#   commits     -- share given to raw commit volume.
#   lines       -- share given to total lines changed (additions + deletions).
#   consistency -- share given to the ratio of active days to total calendar days.
#   recency     -- share given to exponentially decayed recent activity.
#                  Decay factor: 0.85 per calendar week moving back from the
#                  analysis window end date.
#
# weights = { commits = 0.30, lines = 0.25, consistency = 0.25, recency = 0.20 }
"""


def write_init_config(output_path: Path, *, force: bool = False) -> Path:
    """Write a fully annotated default reveille.toml to the specified path.

    Args:
        output_path: Destination path for the generated configuration file.
            The parent directory must exist.
        force: If True, overwrite an existing file without raising an error.
            Defaults to False.

    Returns:
        The resolved absolute path of the written configuration file.

    Raises:
        ConfigurationError: If a file already exists at output_path and
            force is False.
        OutputPathError: If the parent directory does not exist or the
            file cannot be written due to a filesystem error.
    """
    resolved = output_path.resolve()

    if not resolved.parent.exists():
        raise OutputPathError(
            f"Output directory '{resolved.parent}' does not exist. "
            "Create the directory before running `reveille init`."
        )

    if resolved.exists() and not force:
        raise ConfigurationError(
            f"'{resolved}' already exists. "
            "Pass --force to overwrite the existing configuration file."
        )

    try:
        resolved.write_text(_DEFAULT_CONFIG_TEMPLATE, encoding="utf-8")
    except OSError as exc:
        raise OutputPathError(f"Failed to write configuration file to '{resolved}': {exc}") from exc

    return resolved
