"""Config scaffolding for the `reveille init` command.

Provides the annotated default TOML template, the annotated default
.mailmap template, and the write functions that materialise them on
disk. This module has no knowledge of the CLI layer -- it accepts
resolved paths and a force flag, writes files, and returns results.
"""

from __future__ import annotations

from pathlib import Path

from reveille.exceptions import ConfigurationError, OutputPathError

_DEFAULT_CONFIG_TEMPLATE: str = """\
# reveille.toml -- Configuration file for Reveille
#
# Generated by `reveille init`. Uncomment and edit the keys you need.
# All keys are optional. CLI flags always take precedence over values here.
# Full reference:
#   https://github.com/varaprasadchilakanti/reveille/blob/main/docs/USER_GUIDE.md

# ------------------------------------------------------------------------------
# [report] -- Core report parameters
# ------------------------------------------------------------------------------

[report]

# Override the report title displayed in the HTML output.
# Defaults to the repository directory name.
# title = "Engineering Performance Report"

# Output path for the generated HTML file.
# The parent directory must exist at generation time.
# Defaults to ./reveille-report.html at the repository root.
# output = "./reveille-report.html"

# Analyse commits reachable from this branch only.
# Defaults to the repository's currently active branch.
# branch = "main"

# Include only commits on or after this date (YYYY-MM-DD).
# Defaults to the date of the repository's first commit.
# since = "2024-01-01"

# Include only commits on or before this date (YYYY-MM-DD).
# Defaults to today.
# until = "2024-12-31"

# Output format for the generated report.
# Accepted values:
#   html  -- A single self-contained HTML file (default).
#   json  -- A structured JSON file containing ranked contributor statistics
#            and repository metadata, suitable for downstream tooling.
#   csv   -- The ranked contributor table as a UTF-8 CSV file with BOM
#            encoding for direct import into Microsoft Excel.
# format = "html"


# ------------------------------------------------------------------------------
# [filters] -- Contributor and commit filtering
# ------------------------------------------------------------------------------

[filters]

# Exclude contributors with fewer than this many commits in the analysis window.
# Must be a positive integer. Useful for filtering one-off contributors that
# would otherwise distort ranking percentiles in small populations.
# min_commits = 1

# Exclude contributors by name or email address. Case-insensitive.
# Both display name and email forms are accepted. Specify as a TOML array.
# exclude_authors = [
#     "dependabot[bot]",
#     "github-actions[bot]",
# ]


# ------------------------------------------------------------------------------
# [ranking] -- Contributor ranking engine
# ------------------------------------------------------------------------------

[ranking]

# Set to false to omit the contributor ranking table from the output entirely.
# enabled = true

# Metric weights for the composite ranking score.
# All four values must sum to exactly 1.0.
#
#   commits     -- share given to raw commit volume.
#   lines       -- share given to total lines changed (additions + deletions).
#   consistency -- share given to the ratio of active days to total calendar days.
#   recency     -- share given to exponentially decayed recent activity.
#                  Decay factor: 0.85 per calendar week moving back from the
#                  analysis window end date.
#
# weights = { commits = 0.30, lines = 0.25, consistency = 0.25, recency = 0.20 }
"""

_DEFAULT_MAILMAP_TEMPLATE: str = """\
# .mailmap -- Git canonical identity mappings for this repository
#
# Git reads this file to unify commits made under multiple names or
# email addresses into a single canonical identity. Reveille applies
# the same mappings before aggregating contributor metrics, ensuring
# that rankings reflect actual individual output rather than the
# number of identities used.
#
# Generated by `reveille init --mailmap`. Edit to reflect the real
# identities in this repository.
#
# Full specification: https://git-scm.com/docs/gitmailmap
#
#
# ------------------------------------------------------------------------------
# TWO-FIELD FORM -- name correction only
#
#   Canonical Name <commit@email.example>
#
# Updates the display name for every commit from this address.
# The email address is unchanged in the output.
#
# Examples:
#
#   Legal name change:
#   Alice Smith <alice@example.com>
#
#   Normalise inconsistent capitalisation:
#   Bob Jones <b.jones@example.com>
#
#
# ------------------------------------------------------------------------------
# EMAIL-ONLY FORM -- address correction, name untouched
#
#   <canonical@email.example> <alias@email.example>
#
# Maps commits from the alias address to the canonical address while
# leaving each commit's own display name as recorded. Use this when the
# address changed but the name is already correct, or varies legitimately.
#
# Example:
#
#   Address change with no name change:
#   <helen@newcorp.com> <helen@oldcorp.com>
#
#
# ------------------------------------------------------------------------------
# THREE-FIELD FORM -- email alias to canonical identity
#
#   Canonical Name <canonical@email.example> <alias@email.example>
#
# Maps all commits from the alias email to the canonical name and email.
# Use this when a contributor has committed from multiple addresses --
# for example after changing employers, switching between personal and
# work accounts, or merging a GitHub noreply address.
#
# Examples:
#
#   Employer domain change:
#   Alice Smith <alice@newcorp.com> <alice@oldcorp.com>
#
#   GitHub web-interface and merge-button commits (noreply form):
#   Bob Jones <bob@example.com> <12345+bobjones@users.noreply.github.com>
#
#   Personal account used before work account was configured:
#   Carol Chen <carol@corp.com> <carol.chen@gmail.com>
#
#
# ------------------------------------------------------------------------------
# FOUR-FIELD FORM -- name and email alias to canonical identity
#
#   Canonical Name <canonical@email.example> Old Name <old@email.example>
#
# Maps commits made under a specific combination of old name and old email
# to the canonical identity. The entry applies only when both the name and
# the address match, so it is the form to use when several people have
# committed under one shared address -- a default `git config` left in
# place on a build machine, for example. The other forms key on the
# address alone and would rewrite every contributor using it.
#
# Examples:
#
#   Both name and address changed at once:
#   Dan Brown <dan@newcorp.com> Daniel Brown <daniel@oldcorp.com>
#
#   Disentangling two people who shared one address:
#   Dan Brown <dan@corp.com> Dan <build@ci.corp.com>
#   Erica Stone <erica@corp.com> Erica <build@ci.corp.com>
#
#
# ------------------------------------------------------------------------------
# MATCHING NOTES
#
# Names and addresses are matched case-insensitively. Where more than one
# entry could apply, the most specific wins: a four-field entry matching
# both name and address takes precedence over one keyed on address alone.
# A `#` begins a comment that runs to the end of the line.
#
"""


def write_init_config(output_path: Path, *, force: bool = False) -> Path:
    """Write a fully annotated default reveille.toml to the specified path.

    Args:
        output_path: Destination path for the generated configuration file.
            The parent directory must exist.
        force: If True, overwrite an existing file without raising an error.
            Defaults to False.

    Returns:
        The resolved absolute path of the written configuration file.

    Raises:
        ConfigurationError: If a file already exists at output_path and
            force is False.
        OutputPathError: If the parent directory does not exist or the
            file cannot be written due to a filesystem error.
    """
    resolved = output_path.resolve()

    if not resolved.parent.exists():
        raise OutputPathError(
            f"Output directory '{resolved.parent}' does not exist. "
            "Create the directory before running `reveille init`."
        )

    if resolved.exists() and not force:
        raise ConfigurationError(
            f"'{resolved}' already exists. "
            "Pass --force to overwrite the existing configuration file."
        )

    try:
        resolved.write_text(_DEFAULT_CONFIG_TEMPLATE, encoding="utf-8")
    except OSError as exc:
        raise OutputPathError(f"Failed to write configuration file to '{resolved}': {exc}") from exc

    return resolved


def write_mailmap_template(output_path: Path, *, force: bool = False) -> Path | None:
    """Write an annotated .mailmap template to the specified path.

    Unlike write_init_config, an existing file at output_path is not an
    error condition -- .mailmap is a Git-native file the repository may
    already have configured. When the file exists and force is False, the
    write is silently skipped and None is returned.

    Args:
        output_path: Destination path for the .mailmap template.
            The parent directory must exist.
        force: If True, overwrite an existing file. Defaults to False.

    Returns:
        The resolved absolute path of the written file, or None if the
        file already existed and force was False.

    Raises:
        OutputPathError: If the parent directory does not exist or the
            file cannot be written due to a filesystem error.
    """
    resolved = output_path.resolve()

    if not resolved.parent.exists():
        raise OutputPathError(
            f"Output directory '{resolved.parent}' does not exist. "
            "Create the directory before running `reveille init --mailmap`."
        )

    if resolved.exists() and not force:
        return None

    try:
        resolved.write_text(_DEFAULT_MAILMAP_TEMPLATE, encoding="utf-8")
    except OSError as exc:
        raise OutputPathError(f"Failed to write .mailmap template to '{resolved}': {exc}") from exc

    return resolved
